project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: false

website:
  title: "ASM 2022 - Shiny Workshop"
  favicon: images/lter-logo.png
  repo-url: https://github.com/njlyon0/asm-2022_shiny-workshop
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    right:
      - supp_mat.qmd
      - about.qmd
      - icon: github
        href: https://github.com/njlyon0/asm-2022_shiny-workshop
  sidebar: 
    style: "docked"
    background: "secondary"
    search: true
    contents:
      - href: index.qmd
        text: About the Workshop
      - section: "Core Content"
        contents:
          - core_shiny.qmd
          - byo.qmd
      - section: "Bonus Content"
        contents:
          - data.qmd
          - labels.qmd
          - layouts.qmd
          - resources.qmd
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: primary
  margin-footer: |
    <img src="images/nceas-logo.png" width="40%"/>
    <img src="images/lter-logo.png" width="40%"/>

format:
  html:
    theme:
       light: yeti
       dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    