---
title: "deploy"
editor: visual
---

## Deploying your shiny app

We won't cover deploying a shiny app in this session—it's a bit of a convoluted process, and the risk of everyone getting derailed at some point in the process is too high. That being said, deploying is incredibly straightforward once you set everything up right. 

The most common way to deploy apps is via (shinyapps.io)[shinyapps.io]. Shiny lets users host apps for free, but there some limits on size, server allocation, etc.  This method works wonders for most users. Most won't want to look into other options, unless they're creating an app for deployment in a very professional or high-user environment.

A somewhat comprehensive guide to deployment is available here: [https://shiny.rstudio.com/articles/shinyapps.html](https://shiny.rstudio.com/articles/shinyapps.html)

You can see demo apps deployed on shinyapps.io here:
[Workshop Example App](https://lternetwork.shinyapps.io/asm_2022_shiny_workshop_full_app_deploy/)
[LTER Map](https://lternetwork.shinyapps.io/lter_map_redo/?_ga=2.230311068.140765860.1663269972-218790057.1663269972)